import './globals.css'
import { Header, Footer } from './components'
import Head from 'next/head';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        <meta name="viewport" content="initial-scale=1, viewport-fit=cover" />
      </Head>
      <body className='min-h-screen flex flex-col'>
        <Header/>
          <main className='flex-1 flex flex-col my-20'>
            {children}
          </main>
        <Footer/>  
      </body>
    </html>
  )
}
